package za.co.zapper.assessment.domain;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DETAIL".
 */
public class Detail {

    private Long id;
    private String firstName;
    private String lastName;
    private Integer age;
    private String favouriteColour;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Detail() {
    }

    public Detail(Long id) {
        this.id = id;
    }

    public Detail(Long id, String firstName, String lastName, Integer age, String favouriteColour) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.age = age;
        this.favouriteColour = favouriteColour;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public String getFavouriteColour() {
        return favouriteColour;
    }

    public void setFavouriteColour(String favouriteColour) {
        this.favouriteColour = favouriteColour;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
