package za.co.zapper.assessment.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import za.co.zapper.assessment.domain.Detail;
import za.co.zapper.assessment.domain.Master;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig masterDaoConfig;
    private final DaoConfig detailDaoConfig;

    private final MasterDao masterDao;
    private final DetailDao detailDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        masterDaoConfig = daoConfigMap.get(MasterDao.class).clone();
        masterDaoConfig.initIdentityScope(type);

        detailDaoConfig = daoConfigMap.get(DetailDao.class).clone();
        detailDaoConfig.initIdentityScope(type);

        masterDao = new MasterDao(masterDaoConfig, this);
        detailDao = new DetailDao(detailDaoConfig, this);

        registerDao(Master.class, masterDao);
        registerDao(Detail.class, detailDao);
    }
    
    public void clear() {
        masterDaoConfig.getIdentityScope().clear();
        detailDaoConfig.getIdentityScope().clear();
    }

    public MasterDao getMasterDao() {return masterDao;}

    public DetailDao getDetailDao() {
        return detailDao;
    }

}
